/*
 * webPage.c
 *
 *  Created on: 9 jul. 2020
 *      Author: root
 */
#include "webPage.h"

//char HttpWebPage[]="<html><body id=\"body\" onload='carBody()'><p><script>/*<![CDATA[*/var acPan;var tim;function carPan(){var a=new XMLHttpRequest();a.onreadystatechange=function(){if(this.readyState==4&&this.status==200){var g=this.responseText;var f=g.substring(g.indexOf(\"$paneldata\")+10);acPan=g.charAt(g.indexOf(\"$panelnum\")+9);document.getElementById(\"b1\").value=str[acPan];var b=0;for(var c=0;c<6;c++){var e=document.getElementById(\"c\"+c);e.innerHTML=f;var d=0;while((elemento=document.getElementById(\"p\"+d))!=null){elemento.id=\"p\"+d+c;b++;d++}}tim=window.setInterval(function(){carDat(\"GET\",\"/data\")},1000)}};a.open(\"GET\",\"/panel\",true);a.send()}/*]]>*/</script><script>/*<![CDATA[*/var str=[\"Test Drivers\",\"Test Temporizadores\",\"Guardar\",\"Iniciar\",\"Parar\",\"Iniciar todo\",\"Parar todo\"];function carDat(a,b){var c=new XMLHttpRequest();c.onreadystatechange=function(){if(this.readyState==4&&this.status==200){var e=JSON.parse(this.responseText);if(e.panel==acPan){for(j=0;j<6;j++){for(i=0;i<8;i++){var d=document.getElementById(\"p\"+i+j);var f=e.data[i*6+j];if(d.type==\"number\"){if(d.value==\"\"){d.value=f}}else{d.value=str[f];if(f>10){if(f>20){d.style.background=\"#ff6347\"}else{d.style.background=\"#7CFC00\"}}}}}}else{acPan=e.panel;clearTimeout(tim);carPan()}}};c.open(a,b,true);c.send()}/*]]>*/</script><script>/*<![CDATA[*/function guardar(b){var a;a=parseInt(b.slice(2));req=\"/save$\"+acPan+\"$\"+b+\"$data:[\"+document.getElementById(\"p\"+3+a).value;for(i=4;i<7;i++){req=req+\",\"+document.getElementById(\"p\"+i+a).value}req=req+\"]\";carDat(\"POST\",req)}/*]]>*/</script><script>/*<![CDATA[*/function carBody(){var a=new XMLHttpRequest();a.onreadystatechange=function(){if(this.readyState==4&&this.status==200){var b=this.responseText;document.getElementById(\"body\").innerHTML+=b;carPan(\"GET\",\"/panel\")}};a.open(\"GET\",\"/body\",true);a.send()}/*]]>*/</script><script>function envBot(b){var a=new XMLHttpRequest();a.open(\"POST\",\"/button$\"+acPan+\"$\"+b,true);a.send()};</script></p></body></html>";
char HttpWebPage[]="<html> <body id=\"body\" onload='carBody()'> <script>/*<![CDATA[*/var acPan;var tim;function carPan(){var b=new XMLHttpRequest();b.onreadystatechange=function(){if(this.readyState==4&&this.status==200){var h=this.responseText;var k=h.substring(h.indexOf(\"$paneldata\")+10);acPan=h.charAt(h.indexOf(\"$panelnum\")+9);document.getElementById(\"b1\").value=str[acPan];var a=0;for(var n=0;n<6;n++){var l=document.getElementById(\"c\"+n);l.innerHTML=k;var m=0;while((elemento=document.getElementById(\"p\"+m))!=null){elemento.id=\"p\"+m+n;a++;m++}}tim=window.setInterval(function(){carDat(\"GET\",\"/data\")},1000)}};b.open(\"GET\",\"/panel\",true);b.send()}/*]]>*/</script> <script id=\"loadData\">/*<![CDATA[*/function carDat(e,d){var f=new XMLHttpRequest();f.onreadystatechange=function(){if(this.readyState==4&&this.status==200){var b=JSON.parse(this.responseText);if(b.panel==acPan){for(j=0;j<6;j++){for(i=0;i<8;i++){var c=document.getElementById(\"p\"+i+j);var a=b.data[i*6+j];if(c.type==\"number\"){if(c.value==\"\"){c.value=a}}else{c.value=str[a];if(a>20){if(a>30){c.style.background=\"#ff6347\"}else{c.style.background=\"#7CFC00\"}}}}}}else{clearTimeout(tim);carPan()}}};f.open(e,d,true);f.send()}/*]]>*/</script> <script>/*<![CDATA[*/function guardar(c){var d;d=parseInt(c.slice(2));req=\"/save$\"+acPan+\"$\"+c+\"$data:[\"+document.getElementById(\"p\"+3+d).value;for(i=4;i<7;i++){req=req+\",\"+document.getElementById(\"p\"+i+d).value}req=req+\"]\";carDat(\"POST\",req)}/*]]>*/</script> <script>/*<![CDATA[*/function carBody(){var b=new XMLHttpRequest();b.onreadystatechange=function(){if(this.readyState==4&&this.status==200){var d=this.responseText;document.getElementById(\"body\").innerHTML+=d;var a=document.createElement(\"script\");a.innerHTML=document.getElementById(\"etiquetas\").innerHTML;document.head.appendChild(a);carPan(\"GET\",\"/panel\")}};b.open(\"GET\",\"/body\",true);b.send()}/*]]>*/</script> <script>function envBot(c){var d=new XMLHttpRequest();d.open(\"POST\",\"/button$\"+acPan+\"$\"+c,true);d.send()};</script> </body> </html>";

//char HttpBody[]="<div id=\"base\" style=\"width:100%;height:10%\"><table border=\"0\"style=\"width: 100%; height: 100%\"><tbody><tr><td style=\"width:5%;height:100%\"><input type=\"button\" id=\"b0\" onclick='envBot(this.id)' style=\"width:100%;height:100%\"></button></td><td style=\"width:50%;height:100%\"><input type=\"button\" id=\"b1\" style=\"width:100%;height:100%\"></button></td><td style=\"width:5%;height:100%\"><input type=\"button\" id=\"b2\" onclick='envBot(this.id)' style=\"width:100%;height:100%\"></button></td><td style=\"width:40%;height:100%\"><input type=\"button\" id=\"b4\" onclick='envBot(this.id)' style=\"width:100%;height:100%\"></button></td></tr></tbody></table></div><div id=\"panel\" style=\"width:100%;height:90%\"><table border=\"0\"style=\"width: 100%; height: 100%\"><tbody><tr><td id=\"c0\" style=\"width:16.66%;height:100%\"></td><td id=\"c1\" style=\"width:16.66%;height:100%\"></td><td id=\"c2\" style=\"width:16.66%;height:100%\"></td><td id=\"c3\" style=\"width:16.66%;height:100%\"></td><td id=\"c4\" style=\"width:16.66%;height:100%\"></td><td id=\"c5\" style=\"width:16.66%;height:100%\"></td></tr></tbody></table></table></div>";
char HttpBody[]="<script id=etiquetas>var str=[\"Inicio\",\"Test Drivers\",\"Test Temporizadores\",\"Inicio\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",,,,,,,,,\"MARCHA\",\"GUARDAR\",\"PASA\",,,,,,,,\"PARADA\",\"PARAR TODO\",\"Fin\",\"NO PASA\",\"Presionar Pulsador\"];</script> <div id=\"base\" style=\"width:100%;height:10%\"> <table border=\"0\"style=\"width: 100%; height: 100%\"> <tbody> <tr> <td style=\"width:5%;height:100%\"> <input type=\"button\" value=\"<\" id=\"b0\" onclick='envBot(this.id)' style=\"width:100%;height:100%\"></button> </td> <td style=\"width:50%;height:100%\"> <input type=\"button\" id=\"b1\" style=\"width:100%;height:100%\"></button> </td> <td style=\"width:5%;height:100%\"> <input type=\"button\" value=\">\" id=\"b2\" onclick='envBot(this.id)' style=\"width:100%;height:100%\"></button> </td> <td style=\"width:40%;height:100%\"> <input type=\"button\" value=\"Detener Pruebas\" id=\"b4\" onclick='envBot(this.id)' style=\"width:100%;height:100%\"></button> </td> </tr> </tbody> </table> </div> <div id=\"panel\" style=\"width:100%;height:90%\"> <table border=\"0\"style=\"width: 100%; height: 100%\"> <tbody> <tr> <td id=\"c0\" style=\"width:16.66%;height:100%\"></td> <td id=\"c1\" style=\"width:16.66%;height:100%\"></td> <td id=\"c2\" style=\"width:16.66%;height:100%\"></td> <td id=\"c3\" style=\"width:16.66%;height:100%\"></td> <td id=\"c4\" style=\"width:16.66%;height:100%\"></td> <td id=\"c5\" style=\"width:16.66%;height:100%\"></td></tr></tbody></table></table></div>";

char panel0[] = "$panelnum1$paneldata<input type=\"button\" id=\"p0\" style=\"width: 100%;height: 17%;\" ></button><br><input type=\"button\" id=\"p1\" onclick=\'envBot(this.id)\' style=\"width: 100%; height: 17%;\" ></button><br><input type=\"button\" id=\"p2\" style=\"width: 100%; height: 17%;\" ></button><br><label style=\"font-size:1.8vh;\">Parametro 1:</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p3\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">Parametro 2:</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p4\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">Parametro 3:</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p5\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">Parametro 4:</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p6\" style=\"width: 100%; height: 7%;\"></button><br><input type=\"button\" id=\"p7\" value = \"Guardar\" onclick=\'guardar(this.id)\' style=\"width: 100%; height: 10%;\"></button><br>";
char panel1[] = "$panelnum2$paneldata<input type=\"button\" id=\"p0\" style=\"width: 100%;height: 17%;\" ></button><br><input type=\"button\" id=\"p1\" onclick=\'envBot(this.id)\' style=\"width: 100%; height: 17%;\" ></button><br><input type=\"button\" id=\"p2\" style=\"width: 100%; height: 17%;\" ></button><br><label style=\"font-size:1.8vh;\">Parametro 1:</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p3\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">Parametro 2:</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p4\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">Parametro 3:</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p5\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">Parametro 4:</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p6\" style=\"width: 100%; height: 7%;\"></button><br><input type=\"button\" id=\"p7\" value = \"Guardar\" onclick=\'guardar(this.id)\' style=\"width: 100%; height: 10%;\"></button><br>";

//const char panel0[] ="{\"panel\":1,\"ptype\":0,\"x\":6,\"y\":2,\"string\":[1,1,1,1,1,1,2,2,2,2,2,2],\"etype\":[2,2,2,2,2,2,1,1,1,1,1,1]}";
char pageDataA[350]="{\"panel\":1,\"data\":[1,1,1,1,1,1,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2]}";
char pageDataB[350]="{\"panel\":1,\"data\":[1,1,1,1,1,1,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2]}";
char ok[]="OK";
char requestError[] = "HTTP/1.1 400 OK";


char *actualPageData;
char *actualPanel;
uint8_t actualPanelNumber;
