/*
 * webPage.c
 *
 *  Created on: 9 jul. 2020
 *      Author: root
 */
#include "webPage.h"

char HttpWebPage[]="<html><body id=\"body\" onload='carBody()'><script>/*<![CDATA[*/var Pan;var tim;function carPan(){var a=new XMLHttpRequest();a.onreadystatechange=function(){if(this.readyState==4&&this.status==200){var g=this.responseText;var f=g.substring(g.indexOf(\"$paneldata\")+10);Pan=g.charAt(g.indexOf(\"$panelnum\")+9);document.getElementById(\"b1\").value=str[Pan];var b=0;for(var c=0;c<6;c++){var e=document.getElementById(\"c\"+c);e.innerHTML=f;var d=0;while((elemento=document.getElementById(\"p\"+d))!=null){elemento.id=\"p\"+d+c;b++;d++}}tim=window.setInterval(function(){carDat(\"GET\",\"/data\")},1000)}};a.open(\"GET\",\"/panel\",true);a.send()}/*]]>*/</script><script>/*<![CDATA[*/function carDat(a,b){var c=new XMLHttpRequest();c.onreadystatechange=function(){if(this.readyState==4&&this.status==200){var f=JSON.parse(this.responseText);if(f.panel==Pan){for(j=0;j<6;j++){for(i=0;i<8;i++){var e=document.getElementById(\"p\"+i+j);var g=f.data[i*6+j];if(e.type==\"number\"){if(e.value==\"\"){e.value=g}}else{if(i>2&&i<7){e.value=g}else{e.value=str[g];var d;if(g>20){if(g>30){d=\"#ff6347\"}else{d=\"#7CFC00\"}}else{d=\"#F0FFFF\"}e.style.background=d}}}}}else{clearTimeout(tim);carPan()}}};c.open(a,b,true);c.send()}/*]]>*/</script><script>/*<![CDATA[*/function guardar(b){var a;a=parseInt(b.slice(2));req=\"/save$\"+Pan+\"$\"+b+\"$data:[\"+document.getElementById(\"p\"+3+a).value;for(i=4;i<7;i++){req=req+\",\"+document.getElementById(\"p\"+i+a).value}req=req+\"]\";carDat(\"POST\",req)}/*]]>*/</script><script>/*<![CDATA[*/function carBody(){var a=new XMLHttpRequest();a.onreadystatechange=function(){if(this.readyState==4&&this.status==200){var c=this.responseText;document.getElementById(\"body\").innerHTML+=c;var b=document.createElement(\"script\");b.innerHTML=document.getElementById(\"etiquetas\").innerHTML;document.head.appendChild(b);carPan(\"GET\",\"/panel\")}};a.open(\"GET\",\"/body\",true);a.send()}/*]]>*/</script><script>function envBot(b){var a=new XMLHttpRequest();a.open(\"POST\",\"/button$\"+Pan+\"$\"+b,true);a.send()};</script></body></html>";

//char HttpBody[]="<script id=etiquetas>var str=[\"Inicio\",\"Test Drivers\",\"Test Temporizadores\",\"Calibracion\",\"Inicio\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",,,,,,\"-\",\"MARCHA\",\"GUARDAR\",\"PASA\",,,,,,,,\"PARADA\",\"PARAR TODO\",\"Fin\",\"NO PASA\",\"Presionar Pulsador\"];</script> <div id=\"base\" style=\"width:100%;height:10%\"> <table border=\"0\"style=\"width: 100%; height: 100%\"> <tbody> <tr> <td style=\"width:5%;height:100%\"> <input type=\"button\" value=\"<\" id=\"b0\" onclick='envBot(this.id)' style=\"width:100%;height:100%\"></button> </td> <td style=\"width:50%;height:100%\"> <input type=\"button\" id=\"b1\" style=\"width:100%;height:100%\"></button> </td> <td style=\"width:5%;height:100%\"> <input type=\"button\" value=\">\" id=\"b2\" onclick='envBot(this.id)' style=\"width:100%;height:100%\"></button> </td> <td style=\"width:40%;height:100%\"> <input type=\"button\" value=\"Detener Pruebas\" id=\"b4\" onclick='envBot(this.id)' style=\"width:100%;height:100%\"></button> </td> </tr> </tbody> </table> </div> <div id=\"panel\" style=\"width:100%;height:90%\"> <table border=\"0\"style=\"width: 100%; height: 100%\"> <tbody> <tr> <td id=\"c0\" style=\"width:16.66%;height:100%\"></td> <td id=\"c1\" style=\"width:16.66%;height:100%\"></td> <td id=\"c2\" style=\"width:16.66%;height:100%\"></td> <td id=\"c3\" style=\"width:16.66%;height:100%\"></td> <td id=\"c4\" style=\"width:16.66%;height:100%\"></td> <td id=\"c5\" style=\"width:16.66%;height:100%\"></td> </tr> </tbody> </table> </table> </div>";
char HttpBody[]="<script id=etiquetas>var str=[\"Inicio\",\"Test Drivers\",\"Test Temporizadores\",\"Calibracion\",\"Inicio\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Probando\",\"Configurar en T1\",\"Configurar en T2\",,,,\"-\",\"MARCHA\",\"GUARDAR\",\"PASA\",,,,,,,,\"PARADA\",\"PARAR TODO\",\"Fin\",\"NO PASA\",\"Presionar Pulsador\"];</script> <div id=\"base\" style=\"width:100%;height:10%\"> <table border=\"0\"style=\"width: 100%; height: 100%\"> <tbody> <tr> <td style=\"width:5%;height:100%\"> <input type=\"button\" value=\"<\" id=\"b0\" onclick='envBot(this.id)' style=\"width:100%;height:100%\"></button> </td> <td style=\"width:50%;height:100%\"> <input type=\"button\" id=\"b1\" style=\"width:100%;height:100%\"></button> </td> <td style=\"width:5%;height:100%\"> <input type=\"button\" value=\">\" id=\"b2\" onclick='envBot(this.id)' style=\"width:100%;height:100%\"></button> </td> <td style=\"width:40%;height:100%\"> <input type=\"button\" value=\"Detener Pruebas\" id=\"b4\" onclick='envBot(this.id)' style=\"width:100%;height:100%\"></button> </td> </tr> </tbody> </table> </div> <div id=\"panel\" style=\"width:100%;height:90%\"> <table border=\"0\"style=\"width: 100%; height: 100%\"> <tbody> <tr> <td id=\"c0\" style=\"width:16.66%;height:100%\"></td> <td id=\"c1\" style=\"width:16.66%;height:100%\"></td> <td id=\"c2\" style=\"width:16.66%;height:100%\"></td> <td id=\"c3\" style=\"width:16.66%;height:100%\"></td> <td id=\"c4\" style=\"width:16.66%;height:100%\"></td> <td id=\"c5\" style=\"width:16.66%;height:100%\"></td> </tr> </tbody> </table> </table> </div>";

char panel0[] ="$panelnum1$paneldata<input type=\"button\" id=\"p0\" style=\"width: 100%;height: 17%;\" ></button><br><input type=\"button\" id=\"p1\" onclick=\'envBot(this.id)\' style=\"width: 100%; height: 17%;\" ></button><br><input type=\"button\" id=\"p2\" style=\"width: 100%; height: 17%;\" ></button><br><label style=\"font-size:1.8vh;\">Tensión</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p3\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">Corriente</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p4\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">Ganancia CH1</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p5\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">Ganancia CH1</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p6\" style=\"width: 100%; height: 7%;\"></button><br><input type=\"button\" id=\"p7\" value = \"Guardar\" onclick=\'guardar(this.id)\' style=\"width: 100%; height: 10%;\"></button><br>";
char panel1[] ="$panelnum2$paneldata<input type=\"button\" id=\"p0\" style=\"width: 100%;height: 17%;\" ></button><br><input type=\"button\" id=\"p1\" onclick=\'envBot(this.id)\' style=\"width: 100%; height: 17%;\" ></button><br><input type=\"button\" id=\"p2\" style=\"width: 100%; height: 17%;\" ></button><br><label style=\"font-size:1.8vh;\">T1 min</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p3\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">T1 max</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p4\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">T2 min</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p5\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">T2 max</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p6\" style=\"width: 100%; height: 7%;\"></button><br><input type=\"button\" id=\"p7\" value = \"Guardar\" onclick=\'guardar(this.id)\' style=\"width: 100%; height: 10%;\"></button><br>";
char panel2[] ="$panelnum3$paneldata<input type=\"button\" id=\"p0\" style=\"width: 100%;height: 17%;\" ></button><br><input type=\"button\" id=\"p1\" onclick=\'envBot(this.id)\' style=\"width: 100%; height: 17%;\" ></button><br><input type=\"button\" id=\"p2\" style=\"width: 100%; height: 17%;\" ></button><br><label style=\"font-size:1.8vh;\">ADC1</label><br><input type=\"button\" min=\"0\" max=\"9999\" id=\"p3\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">ADC2</label><br><input type=\"button\" min=\"0\" max=\"9999\" id=\"p4\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">Ganancia CH1</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p5\" style=\"width: 100%; height: 7%;\" ></button><br><label style=\"font-size:1.8vh;\">Ganancia CH1</label><br><input type=\"number\" min=\"0\" max=\"9999\" id=\"p6\" style=\"width: 100%; height: 7%;\"></button><br><input type=\"button\" id=\"p7\" value = \"Guardar\" onclick=\'guardar(this.id)\' style=\"width: 100%; height: 10%;\"></button><br>";

char pageDataA[350]="{\"panel\":1,\"data\":[1,1,1,1,1,1,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2]}";
char pageDataB[350]="{\"panel\":1,\"data\":[1,1,1,1,1,1,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2]}";
char ok[]="OK";
char requestError[] = "HTTP/1.1 400 OK";


char *actualPageData;
char *actualPanel;
uint8_t actualPanelNumber;
